services:
  app:
    image: jellyfin/jellyfin
    user: 1000:1000
    networks: 
      - outside
    volumes:
      - jelly-config:/config
      - jelly-cache:/cache
      - mnt-public:/media/public:ro
      - mnt-tyler:/media/tyler:ro
# Optional - extra fonts to be used during transcoding with subtitle burn-in
#       - type: bind
#               source: /path/to/fonts
#               target: /usr/local/share/fonts/custom
#               read_only: true
                                                                                                    
# Optional - alternative address used for autodiscovery
#   environment:
#     - JELLYFIN_PublishedServerUrl=http://example.com
# Optional - may be necessary for docker healthcheck to pass if running in host network mode
#   extra_hosts:
#      - 'host.docker.internal:host-gateway'

volumes:
  jelly-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1
      device: ":/srv/docker/jellfin/config"
  jelly-cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1
      device: ":/srv/docker/jellfin/cache"
  mnt-public:
  mnt-tyler:

networks:
  outside:
    external: true
    name: "host"
