services:
  app:
    image: jellyfin/jellyfin
    user: 1000:1000
    networks: 
      - outside
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - mnt-public:/media/public:ro
      - mnt-tyler:/media/tyler:ro
# Optional - extra fonts to be used during transcoding with subtitle burn-in
#       - type: bind
#               source: /path/to/fonts
#               target: /usr/local/share/fonts/custom
#               read_only: true
                                                                                                    
# Optional - alternative address used for autodiscovery
#   environment:
#     - JELLYFIN_PublishedServerUrl=http://example.com
# Optional - may be necessary for docker healthcheck to pass if running in host network mode
#   extra_hosts:
#      - 'host.docker.internal:host-gateway'

volumes:
  jellyfin-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.tyler-clark.com,rw,vers=4.1
      device: ":/srv/docker/jellyfin/config"
  jellyfin-cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.tyler-clark.com,rw,vers=4.1
      device: ":/srv/docker/jellyfin/cache"
  mnt-public:
    external: true
  mnt-tyler:
    external: true

networks:
  outside:
    external: true
    name: "host"
